### ISSUE TITLE
Make Property.java configurable from InitDDS.java

### ISSUE THREAD

**Issue by utsengar** [sjsu-cmpe/vyuudha#17]
The requirement is:
1. If we pass an argument (path of config folder) to com.dds.init.InitDDS, then take that folder as the config folder and populate the configuration.  
2. If it's not passed, then take up the default config folder.

I have tweaked com.dds.init.InitDDS.java.

@ravidontharaju You need to follow the instructions in InitDDS.java. No need to optimize anything else there. We just need to make it work.

**Comment by ravidontharaju** [comment]
Resolved.
https://github.com/sjsu-cmpe/vyuudha/commit/73fc57a2f3822c1221b7c4f625f7d210c217fd8b

Variables in GlobalVariables have been made private and getters are being used.
- Ravi
