### ISSUE TITLE
BDB problem

### ISSUE THREAD

**Issue by ravidontharaju** [sjsu-cmpe/vyuudha#5]
To inherit all functions of core BDB api, we need to create a second layer of abstraction.
Layer 1 would contain the configuration information a
Layer 2 will contain the actual BDB calls.
- Ravi

**Comment by utsengar** [comment]
Why cant configuration info and BDB calls be in the same class? BDB in PV has a similar approach.

**Comment by utsengar** [comment]
is it fixed?

**Comment by ravidontharaju** [comment]
Fixed. BDB super class needs configuration as a parameter and hence we have two classes. One for configuration and the other for persistence calls. This needs to be done for MongoDB and MySQL too.
